name: prep_check
description: Kitchen prep inventory and chat app (Flutter + Firebase)
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  cloud_functions: ^6.0.3
  google_sign_in: ^6.2.1
  firebase_ui_auth: ^3.0.0
  firebase_ui_oauth_google: ^2.0.0
  go_router: ^16.2.5
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  intl: ^0.20.2
  uuid: ^4.3.3
  timezone: ^0.10.1
  firebase_app_check: ^0.4.1+1
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  youtube_player_flutter: ^9.1.3
  webview_flutter: ^4.13.0
  video_compress: ^3.1.4
  shared_preferences: ^2.5.3
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  chewie: ^1.13.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  assets:
    - assets/app_icon.png
    - assets/splash.png
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#121418"   # optional: matches your artwork bg
  adaptive_icon_foreground: assets/app_icon.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#121418"
  image: assets/splash.png
  android_12:
    color: "#121418"
    image: assets/splash.png
  android_gravity: center
  ios_content_mode: center
  web: false